# 开发环境
spring:
  datasource: # 数据源
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/petdb?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      max-active: 20        # 最大连接数
      max-wait: 6000        # 最大等待时间（毫秒）
      min-idle: 1           # 最小空闲连接
      test-on-borrow: true  # 使用时检测连接是否有效
      test-on-return: true  # 放回时检测连接是否有效

mybatis:
  mapper-locations: classpath*:com/example/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml