package com.example.dao;

import com.example.pojo.PetMovie;
import java.util.List;

public interface PetMovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_movie
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_movie
     *
     * @mbg.generated
     */
    int insert(PetMovie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_movie
     *
     * @mbg.generated
     */
    PetMovie selectByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_movie
     *
     * @mbg.generated
     */
    List<PetMovie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_movie
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PetMovie row);
}