package com.example.dao;

import com.example.pojo.PetPost;
import java.util.List;

public interface PetPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_post
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_post
     *
     * @mbg.generated
     */
    int insert(PetPost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_post
     *
     * @mbg.generated
     */
    PetPost selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_post
     *
     * @mbg.generated
     */
    List<PetPost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_post
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PetPost row);
}