package com.example.dao;

import com.example.pojo.PetSpecie;
import java.util.List;

public interface PetSpecieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_specie
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer specieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_specie
     *
     * @mbg.generated
     */
    int insert(PetSpecie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_specie
     *
     * @mbg.generated
     */
    PetSpecie selectByPrimaryKey(Integer specieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_specie
     *
     * @mbg.generated
     */
    List<PetSpecie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_specie
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PetSpecie row);
}