package com.example.dao;

import com.example.pojo.PostComment;
import java.util.List;

public interface PostCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated
     */
    int insert(PostComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated
     */
    PostComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated
     */
    List<PostComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PostComment row);
}