package com.example.dao;

import com.example.pojo.Review;
import java.util.List;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer reviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    int insert(Review row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    Review selectByPrimaryKey(Integer reviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    List<Review> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Review row);
}