package com.example.pojo;

import java.util.Date;

public class PetInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.pet_id
     *
     * @mbg.generated
     */
    private Integer petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.pet_name
     *
     * @mbg.generated
     */
    private String petName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.variety_id
     *
     * @mbg.generated
     */
    private Integer varietyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.pet_sex
     *
     * @mbg.generated
     */
    private String petSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.pet_birthday
     *
     * @mbg.generated
     */
    private Date petBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.is_neutered
     *
     * @mbg.generated
     */
    private Integer isNeutered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.vaccine_status
     *
     * @mbg.generated
     */
    private String vaccineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_info.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.pet_id
     *
     * @return the value of pet_info.pet_id
     *
     * @mbg.generated
     */
    public Integer getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.pet_id
     *
     * @param petId the value for pet_info.pet_id
     *
     * @mbg.generated
     */
    public void setPetId(Integer petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.user_id
     *
     * @return the value of pet_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.user_id
     *
     * @param userId the value for pet_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.pet_name
     *
     * @return the value of pet_info.pet_name
     *
     * @mbg.generated
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.pet_name
     *
     * @param petName the value for pet_info.pet_name
     *
     * @mbg.generated
     */
    public void setPetName(String petName) {
        this.petName = petName == null ? null : petName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.variety_id
     *
     * @return the value of pet_info.variety_id
     *
     * @mbg.generated
     */
    public Integer getVarietyId() {
        return varietyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.variety_id
     *
     * @param varietyId the value for pet_info.variety_id
     *
     * @mbg.generated
     */
    public void setVarietyId(Integer varietyId) {
        this.varietyId = varietyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.pet_sex
     *
     * @return the value of pet_info.pet_sex
     *
     * @mbg.generated
     */
    public String getPetSex() {
        return petSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.pet_sex
     *
     * @param petSex the value for pet_info.pet_sex
     *
     * @mbg.generated
     */
    public void setPetSex(String petSex) {
        this.petSex = petSex == null ? null : petSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.pet_birthday
     *
     * @return the value of pet_info.pet_birthday
     *
     * @mbg.generated
     */
    public Date getPetBirthday() {
        return petBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.pet_birthday
     *
     * @param petBirthday the value for pet_info.pet_birthday
     *
     * @mbg.generated
     */
    public void setPetBirthday(Date petBirthday) {
        this.petBirthday = petBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.is_neutered
     *
     * @return the value of pet_info.is_neutered
     *
     * @mbg.generated
     */
    public Integer getIsNeutered() {
        return isNeutered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.is_neutered
     *
     * @param isNeutered the value for pet_info.is_neutered
     *
     * @mbg.generated
     */
    public void setIsNeutered(Integer isNeutered) {
        this.isNeutered = isNeutered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.vaccine_status
     *
     * @return the value of pet_info.vaccine_status
     *
     * @mbg.generated
     */
    public String getVaccineStatus() {
        return vaccineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.vaccine_status
     *
     * @param vaccineStatus the value for pet_info.vaccine_status
     *
     * @mbg.generated
     */
    public void setVaccineStatus(String vaccineStatus) {
        this.vaccineStatus = vaccineStatus == null ? null : vaccineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.created_at
     *
     * @return the value of pet_info.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.created_at
     *
     * @param createdAt the value for pet_info.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_info.updated_at
     *
     * @return the value of pet_info.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_info.updated_at
     *
     * @param updatedAt the value for pet_info.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}