package com.example.pojo;

import java.util.Date;

public class PetPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.post_id
     *
     * @mbg.generated
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.post_content
     *
     * @mbg.generated
     */
    private String postContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.post_images
     *
     * @mbg.generated
     */
    private String postImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.post_view
     *
     * @mbg.generated
     */
    private Integer postView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.post_like
     *
     * @mbg.generated
     */
    private Integer postLike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_post.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.post_id
     *
     * @return the value of pet_post.post_id
     *
     * @mbg.generated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.post_id
     *
     * @param postId the value for pet_post.post_id
     *
     * @mbg.generated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.user_id
     *
     * @return the value of pet_post.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.user_id
     *
     * @param userId the value for pet_post.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.post_content
     *
     * @return the value of pet_post.post_content
     *
     * @mbg.generated
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.post_content
     *
     * @param postContent the value for pet_post.post_content
     *
     * @mbg.generated
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.post_images
     *
     * @return the value of pet_post.post_images
     *
     * @mbg.generated
     */
    public String getPostImages() {
        return postImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.post_images
     *
     * @param postImages the value for pet_post.post_images
     *
     * @mbg.generated
     */
    public void setPostImages(String postImages) {
        this.postImages = postImages == null ? null : postImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.post_view
     *
     * @return the value of pet_post.post_view
     *
     * @mbg.generated
     */
    public Integer getPostView() {
        return postView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.post_view
     *
     * @param postView the value for pet_post.post_view
     *
     * @mbg.generated
     */
    public void setPostView(Integer postView) {
        this.postView = postView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.post_like
     *
     * @return the value of pet_post.post_like
     *
     * @mbg.generated
     */
    public Integer getPostLike() {
        return postLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.post_like
     *
     * @param postLike the value for pet_post.post_like
     *
     * @mbg.generated
     */
    public void setPostLike(Integer postLike) {
        this.postLike = postLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.created_at
     *
     * @return the value of pet_post.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.created_at
     *
     * @param createdAt the value for pet_post.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_post.updated_at
     *
     * @return the value of pet_post.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_post.updated_at
     *
     * @param updatedAt the value for pet_post.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}