package com.example.dao;

import com.example.pojo.ExpComment;
import java.util.List;

public interface ExpCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_comment
     *
     * @mbg.generated
     */
    int insert(ExpComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_comment
     *
     * @mbg.generated
     */
    ExpComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_comment
     *
     * @mbg.generated
     */
    List<ExpComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exp_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExpComment row);
}