package com.example.dao;

import com.example.pojo.UserAccount;

import java.util.Date;
import java.util.List;

public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated
     */
    int insert(UserAccount row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated
     */
    UserAccount selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated
     */
    List<UserAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserAccount row);

    Integer findCountByUsername(String username);

    UserAccount findRowByUsernameAndPassword(String username, String password);

    Date findUpdateAtByUserId(int userId);

    String findQuestionByUsername(String username);

    String findAnswerByOthers(UserAccount account);

    int updatePasswordByOthers(UserAccount account);
}