package com.example.pojo;

import java.util.Date;

public class ExpComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exp_comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exp_comment.exp_id
     *
     * @mbg.generated
     */
    private Integer expId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exp_comment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exp_comment.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exp_comment.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exp_comment.chat_content
     *
     * @mbg.generated
     */
    private String chatContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exp_comment.comment_id
     *
     * @return the value of exp_comment.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exp_comment.comment_id
     *
     * @param commentId the value for exp_comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exp_comment.exp_id
     *
     * @return the value of exp_comment.exp_id
     *
     * @mbg.generated
     */
    public Integer getExpId() {
        return expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exp_comment.exp_id
     *
     * @param expId the value for exp_comment.exp_id
     *
     * @mbg.generated
     */
    public void setExpId(Integer expId) {
        this.expId = expId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exp_comment.user_id
     *
     * @return the value of exp_comment.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exp_comment.user_id
     *
     * @param userId the value for exp_comment.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exp_comment.created_at
     *
     * @return the value of exp_comment.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exp_comment.created_at
     *
     * @param createdAt the value for exp_comment.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exp_comment.updated_at
     *
     * @return the value of exp_comment.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exp_comment.updated_at
     *
     * @param updatedAt the value for exp_comment.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exp_comment.chat_content
     *
     * @return the value of exp_comment.chat_content
     *
     * @mbg.generated
     */
    public String getChatContent() {
        return chatContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exp_comment.chat_content
     *
     * @param chatContent the value for exp_comment.chat_content
     *
     * @mbg.generated
     */
    public void setChatContent(String chatContent) {
        this.chatContent = chatContent == null ? null : chatContent.trim();
    }
}