package com.example.pojo;

import java.util.Date;

public class PetKnowledge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.kno_id
     *
     * @mbg.generated
     */
    private Integer knoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.kno_title
     *
     * @mbg.generated
     */
    private String knoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.kno_category
     *
     * @mbg.generated
     */
    private String knoCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.specie_id
     *
     * @mbg.generated
     */
    private Integer specieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.variety_id
     *
     * @mbg.generated
     */
    private Integer varietyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.kno_images
     *
     * @mbg.generated
     */
    private String knoImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_knowledge.kno_content
     *
     * @mbg.generated
     */
    private String knoContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.kno_id
     *
     * @return the value of pet_knowledge.kno_id
     *
     * @mbg.generated
     */
    public Integer getKnoId() {
        return knoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.kno_id
     *
     * @param knoId the value for pet_knowledge.kno_id
     *
     * @mbg.generated
     */
    public void setKnoId(Integer knoId) {
        this.knoId = knoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.kno_title
     *
     * @return the value of pet_knowledge.kno_title
     *
     * @mbg.generated
     */
    public String getKnoTitle() {
        return knoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.kno_title
     *
     * @param knoTitle the value for pet_knowledge.kno_title
     *
     * @mbg.generated
     */
    public void setKnoTitle(String knoTitle) {
        this.knoTitle = knoTitle == null ? null : knoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.kno_category
     *
     * @return the value of pet_knowledge.kno_category
     *
     * @mbg.generated
     */
    public String getKnoCategory() {
        return knoCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.kno_category
     *
     * @param knoCategory the value for pet_knowledge.kno_category
     *
     * @mbg.generated
     */
    public void setKnoCategory(String knoCategory) {
        this.knoCategory = knoCategory == null ? null : knoCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.specie_id
     *
     * @return the value of pet_knowledge.specie_id
     *
     * @mbg.generated
     */
    public Integer getSpecieId() {
        return specieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.specie_id
     *
     * @param specieId the value for pet_knowledge.specie_id
     *
     * @mbg.generated
     */
    public void setSpecieId(Integer specieId) {
        this.specieId = specieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.variety_id
     *
     * @return the value of pet_knowledge.variety_id
     *
     * @mbg.generated
     */
    public Integer getVarietyId() {
        return varietyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.variety_id
     *
     * @param varietyId the value for pet_knowledge.variety_id
     *
     * @mbg.generated
     */
    public void setVarietyId(Integer varietyId) {
        this.varietyId = varietyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.kno_images
     *
     * @return the value of pet_knowledge.kno_images
     *
     * @mbg.generated
     */
    public String getKnoImages() {
        return knoImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.kno_images
     *
     * @param knoImages the value for pet_knowledge.kno_images
     *
     * @mbg.generated
     */
    public void setKnoImages(String knoImages) {
        this.knoImages = knoImages == null ? null : knoImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.created_at
     *
     * @return the value of pet_knowledge.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.created_at
     *
     * @param createdAt the value for pet_knowledge.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.updated_at
     *
     * @return the value of pet_knowledge.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.updated_at
     *
     * @param updatedAt the value for pet_knowledge.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_knowledge.kno_content
     *
     * @return the value of pet_knowledge.kno_content
     *
     * @mbg.generated
     */
    public String getKnoContent() {
        return knoContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_knowledge.kno_content
     *
     * @param knoContent the value for pet_knowledge.kno_content
     *
     * @mbg.generated
     */
    public void setKnoContent(String knoContent) {
        this.knoContent = knoContent == null ? null : knoContent.trim();
    }
}