package com.example.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class PetMovie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.movie_id
     *
     * @mbg.generated
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.movie_title
     *
     * @mbg.generated
     */
    private String movieTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.movie_director
     *
     * @mbg.generated
     */
    private String movieDirector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.movie_rating
     *
     * @mbg.generated
     */
    private BigDecimal movieRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.release_date
     *
     * @mbg.generated
     */
    private Date releaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.movie_url
     *
     * @mbg.generated
     */
    private String movieUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.move_poster
     *
     * @mbg.generated
     */
    private String movePoster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.shelf_status
     *
     * @mbg.generated
     */
    private Integer shelfStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_movie.movie_desc
     *
     * @mbg.generated
     */
    private String movieDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.movie_id
     *
     * @return the value of pet_movie.movie_id
     *
     * @mbg.generated
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.movie_id
     *
     * @param movieId the value for pet_movie.movie_id
     *
     * @mbg.generated
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.movie_title
     *
     * @return the value of pet_movie.movie_title
     *
     * @mbg.generated
     */
    public String getMovieTitle() {
        return movieTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.movie_title
     *
     * @param movieTitle the value for pet_movie.movie_title
     *
     * @mbg.generated
     */
    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle == null ? null : movieTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.movie_director
     *
     * @return the value of pet_movie.movie_director
     *
     * @mbg.generated
     */
    public String getMovieDirector() {
        return movieDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.movie_director
     *
     * @param movieDirector the value for pet_movie.movie_director
     *
     * @mbg.generated
     */
    public void setMovieDirector(String movieDirector) {
        this.movieDirector = movieDirector == null ? null : movieDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.movie_rating
     *
     * @return the value of pet_movie.movie_rating
     *
     * @mbg.generated
     */
    public BigDecimal getMovieRating() {
        return movieRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.movie_rating
     *
     * @param movieRating the value for pet_movie.movie_rating
     *
     * @mbg.generated
     */
    public void setMovieRating(BigDecimal movieRating) {
        this.movieRating = movieRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.release_date
     *
     * @return the value of pet_movie.release_date
     *
     * @mbg.generated
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.release_date
     *
     * @param releaseDate the value for pet_movie.release_date
     *
     * @mbg.generated
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.movie_url
     *
     * @return the value of pet_movie.movie_url
     *
     * @mbg.generated
     */
    public String getMovieUrl() {
        return movieUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.movie_url
     *
     * @param movieUrl the value for pet_movie.movie_url
     *
     * @mbg.generated
     */
    public void setMovieUrl(String movieUrl) {
        this.movieUrl = movieUrl == null ? null : movieUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.move_poster
     *
     * @return the value of pet_movie.move_poster
     *
     * @mbg.generated
     */
    public String getMovePoster() {
        return movePoster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.move_poster
     *
     * @param movePoster the value for pet_movie.move_poster
     *
     * @mbg.generated
     */
    public void setMovePoster(String movePoster) {
        this.movePoster = movePoster == null ? null : movePoster.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.shelf_status
     *
     * @return the value of pet_movie.shelf_status
     *
     * @mbg.generated
     */
    public Integer getShelfStatus() {
        return shelfStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.shelf_status
     *
     * @param shelfStatus the value for pet_movie.shelf_status
     *
     * @mbg.generated
     */
    public void setShelfStatus(Integer shelfStatus) {
        this.shelfStatus = shelfStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.created_at
     *
     * @return the value of pet_movie.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.created_at
     *
     * @param createdAt the value for pet_movie.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.updated_at
     *
     * @return the value of pet_movie.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.updated_at
     *
     * @param updatedAt the value for pet_movie.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_movie.movie_desc
     *
     * @return the value of pet_movie.movie_desc
     *
     * @mbg.generated
     */
    public String getMovieDesc() {
        return movieDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_movie.movie_desc
     *
     * @param movieDesc the value for pet_movie.movie_desc
     *
     * @mbg.generated
     */
    public void setMovieDesc(String movieDesc) {
        this.movieDesc = movieDesc == null ? null : movieDesc.trim();
    }
}