package com.example.pojo;

import java.util.Date;

public class PetVariety {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_variety.variety_id
     *
     * @mbg.generated
     */
    private Integer varietyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_variety.specie_id
     *
     * @mbg.generated
     */
    private Integer specieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_variety.variety_name
     *
     * @mbg.generated
     */
    private String varietyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_variety.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_variety.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_variety.variety_id
     *
     * @return the value of pet_variety.variety_id
     *
     * @mbg.generated
     */
    public Integer getVarietyId() {
        return varietyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_variety.variety_id
     *
     * @param varietyId the value for pet_variety.variety_id
     *
     * @mbg.generated
     */
    public void setVarietyId(Integer varietyId) {
        this.varietyId = varietyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_variety.specie_id
     *
     * @return the value of pet_variety.specie_id
     *
     * @mbg.generated
     */
    public Integer getSpecieId() {
        return specieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_variety.specie_id
     *
     * @param specieId the value for pet_variety.specie_id
     *
     * @mbg.generated
     */
    public void setSpecieId(Integer specieId) {
        this.specieId = specieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_variety.variety_name
     *
     * @return the value of pet_variety.variety_name
     *
     * @mbg.generated
     */
    public String getVarietyName() {
        return varietyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_variety.variety_name
     *
     * @param varietyName the value for pet_variety.variety_name
     *
     * @mbg.generated
     */
    public void setVarietyName(String varietyName) {
        this.varietyName = varietyName == null ? null : varietyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_variety.created_at
     *
     * @return the value of pet_variety.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_variety.created_at
     *
     * @param createdAt the value for pet_variety.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_variety.updated_at
     *
     * @return the value of pet_variety.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_variety.updated_at
     *
     * @param updatedAt the value for pet_variety.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}