package com.example.pojo;

import java.util.Date;

public class UserChat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.chat_id
     *
     * @mbg.generated
     */
    private Integer chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.initiator_id
     *
     * @mbg.generated
     */
    private Integer initiatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_chat.chat_content
     *
     * @mbg.generated
     */
    private String chatContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.chat_id
     *
     * @return the value of user_chat.chat_id
     *
     * @mbg.generated
     */
    public Integer getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.chat_id
     *
     * @param chatId the value for user_chat.chat_id
     *
     * @mbg.generated
     */
    public void setChatId(Integer chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.initiator_id
     *
     * @return the value of user_chat.initiator_id
     *
     * @mbg.generated
     */
    public Integer getInitiatorId() {
        return initiatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.initiator_id
     *
     * @param initiatorId the value for user_chat.initiator_id
     *
     * @mbg.generated
     */
    public void setInitiatorId(Integer initiatorId) {
        this.initiatorId = initiatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.user_id
     *
     * @return the value of user_chat.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.user_id
     *
     * @param userId the value for user_chat.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.created_at
     *
     * @return the value of user_chat.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.created_at
     *
     * @param createdAt the value for user_chat.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.updated_at
     *
     * @return the value of user_chat.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.updated_at
     *
     * @param updatedAt the value for user_chat.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_chat.chat_content
     *
     * @return the value of user_chat.chat_content
     *
     * @mbg.generated
     */
    public String getChatContent() {
        return chatContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_chat.chat_content
     *
     * @param chatContent the value for user_chat.chat_content
     *
     * @mbg.generated
     */
    public void setChatContent(String chatContent) {
        this.chatContent = chatContent == null ? null : chatContent.trim();
    }
}